name: Trigger auto deployment for test-ferry-spring-export-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/test-ferry-spring-export-app-AutoDeployTrigger-e671e752-d3f3-4b01-ae32-c8a815060b7d.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTFERRYSPRINGEXPORTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTFERRYSPRINGEXPORTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTFERRYSPRINGEXPORTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          containerAppName: test-ferry-spring-export-app
          resourceGroup: Test-Ferry-System
